spring.application.name=vaulty-api

spring.datasource.url=jdbc:postgresql://localhost:5432/vaulty
spring.datasource.username=vaulty
spring.datasource.password=vaulty

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true